configuration:
  project-type: MS

  error-messages:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.

  obfuscation:
    body-fields: []
    headers: []

  rules:
    directory: rules/
    strategies:
      DiscountRule: discount_rules.drl