version: '3.1'
services:
  poc-jenkins:
    container_name: poc-jenkins
    image: miguelarmasabt/poc-jenkins:v1.0.1
    restart: on-failure
    ports:
      - "8181:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - dev_cicd_environment
  poc-sonarqube:
    container_name: poc-sonarqube
    image: sonarqube:8.7.1-community
    restart: on-failure
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - dev_cicd_environment
volumes:
  jenkins_home:
networks:
  dev_cicd_environment:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
        - subnet: "2001:3974:3979::/64"
          gateway: "2001:3974:3979::1"
